// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iapficetpkcgchiupzvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhcGZpY2V0cGtjZ2NoaXVwenZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzkwODQsImV4cCI6MjA2MDM1NTA4NH0.rrRRP4iVt3UdC8onT2trGetLK8M695SSVxqVAwUh8EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);