
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfpznvadpmnhvbnzmdzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcHpudmFkcG1uaHZibnptZHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTQzMTcsImV4cCI6MjA1OTU5MDMxN30.K6-qmaGwcgwJeNxJPXqGZSDwM8W0i4jkhvHFnonsL1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
